#################################
# Port Number
#################################
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  banner:
    location: banner/banner.txt

  application:
    name: Blog_Security

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    encoding: UTF-8

  #################################
  # MySQL Setting
  #################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pip_test?serverTimezone=UTC
    username: root
    password: 1234

  #################################
  # JPA Setting
  #################################
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    #    show-sql: true   # 쿼리문 확인
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false



  ###############################
  # Security User
  ###############################
  security:
    user:
      name: hong@test.com
      password: 1111

###############################
# Log info
###############################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


